import { BaseNetwork } from "@/config/interfaces";
import * as ALL_NETWORKS from "@/config/networks";

export const TEST_BRIDGE_NETWORKS: BaseNetwork[] = [
  ALL_NETWORKS.AVALANCHE_TESTNET,
  ALL_NETWORKS.FANTOM_TESTNET,
  ALL_NETWORKS.GOERLI_TESTNET,
  ALL_NETWORKS.MUMBAI_TESTNET,
  ALL_NETWORKS.OPTIMISM_TESTNET,
];

export const MAIN_BRIDGE_IN_NETWORKS: BaseNetwork[] = [
  ALL_NETWORKS.ETH_MAINNET,
  ALL_NETWORKS.NOBLE,
  ALL_NETWORKS.GRAVITY_BRIDGE,
  ALL_NETWORKS.INJECTIVE,

];
export const MAIN_BRIDGE_OUT_NETWORKS: BaseNetwork[] = MAIN_BRIDGE_IN_NETWORKS;
